# Generated by Django 2.0.2 on 2018-02-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='major',
            field=models.CharField(default='undefined', max_length=20),
            preserve_default=False,
        ),
    ]
