# Generated by Django 2.0.2 on 2018-02-20 03:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_customuser_major'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Profile',
        ),
    ]
