# Generated by Django 2.0.2 on 2018-02-22 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('property_name', models.CharField(default='', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('cost', models.PositiveIntegerField(default=0)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('property_type', models.CharField(choices=[('a', 'apartment'), ('c', 'condo'), ('t', 'townhouse'), ('h', 'house')], max_length=10)),
                ('number_of_rooms', models.PositiveSmallIntegerField()),
                ('garages', models.PositiveSmallIntegerField()),
                ('creator_id', models.PositiveIntegerField()),
                ('creator_email', models.CharField(max_length=50)),
                ('creator_phone', models.CharField(blank=True, default='', max_length=10)),
                ('creator_gender', models.CharField(max_length=10)),
                ('creator_major', models.CharField(max_length=20)),
                ('creator_year', models.PositiveSmallIntegerField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Room')),
            ],
        ),
    ]
