# Generated by Django 2.0.2 on 2018-02-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='property_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
