# Generated by Django 2.0.2 on 2018-02-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180212_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='visists',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
