# Generated by Django 2.0.2 on 2018-02-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180213_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(default='No Description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='visists',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
