# Generated by Django 2.0.2 on 2018-02-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180213_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
