# Generated by Django 2.0.2 on 2018-02-15 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180214_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='photo',
            new_name='thumbnail',
        ),
    ]
