# Generated by Django 2.0.2 on 2018-02-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_room_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
