# Generated by Django 2.0.2 on 2018-02-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180214_1942'),
        ('home', '0008_auto_20180215_1241'),
    ]

    operations = [
    ]
