# Generated by Django 2.0.2 on 2018-02-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_room_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='creator_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
