# Generated by Django 2.0.2 on 2018-02-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_room_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='garages',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='property_type',
            field=models.CharField(choices=[('a', 'apartment'), ('c', 'condo'), ('t', 'townhouse'), ('h', 'house')], default='a', max_length=10),
            preserve_default=False,
        ),
    ]
