# Generated by Django 2.0.2 on 2018-02-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180222_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='creator_gender',
            field=models.CharField(default='m', max_length=10),
            preserve_default=False,
        ),
    ]
