# Generated by Django 2.0.2 on 2018-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_room_creator_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='creator_phone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
