# Generated by Django 2.0.2 on 2018-02-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180222_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='creator_major',
            field=models.CharField(default='Computer Science', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='creator_year',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
